### ISSUE TITLE
FriendCore segfaults when trying to access mounted server filesystem

### ISSUE THREAD

**Issue by dm8tbr** [FriendUPCloud/friendup#31]
Mounted the server filesystem as "Server:" and had it added to the desktop.
Remote directory: '/'
When opening the folder (or after restarting FriendCore reloading the folder contents) FriendCore dies with the below backtrace:

```
Thread 10 "FriendCore" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe99e4700 (LWP 17470)]
0x00007ffff59fdcc0 in _IO_vfprintf_internal (s=s@entry=0x7fffe99e0460, format=<optimized out>, format@entry=0x7fffa73c80d2 " \"Filename\":\"%s\",", ap=ap@entry=0x7fffe99e0588) at vfprintf.c:1632
1632    vfprintf.c: No such file or directory.
(gdb) bt
#0  0x00007ffff59fdcc0 in _IO_vfprintf_internal (s=s@entry=0x7fffe99e0460, format=<optimized out>, format@entry=0x7fffa73c80d2 " \"Filename\":\"%s\",", ap=ap@entry=0x7fffe99e0588) at vfprintf.c:1632
#1  0x00007ffff5a1f1cb in __IO_vsprintf (string=0x7fffe99e0690 " \"Filename\":\"", format=0x7fffa73c80d2 " \"Filename\":\"%s\",", args=args@entry=0x7fffe99e0588) at iovsprintf.c:42
#2  0x00007ffff5a049c7 in __sprintf (s=<optimized out>, format=<optimized out>) at sprintf.c:32
#3  0x00007fffa73c3f32 in FillStat (bs=0x7fff800026d0, nf=0x7fffe99e0b00, d=0x6fc3a0, path=0x7fff80005700 "/blubb.tar.bz2") at fsysdyn/fsysinram.c:609
#4  0x00007fffa6fa73f3 in Dir (s=0x6fc3a0, path=0x7fff800008c0 "") at fsysdyn/fsyslocal.c:1287
#5  0x0000000000451e8e in ?? ()
#6  0x0000000000000000 in ?? ()
```

**Comment by stefkosdev** [comment]
Hey

I fixed this issue in our repository.
We have plan to update github shortly.

Regards
